name: Deploy Angular to Netlify

on:
  push:
    branches: [ "main" ]  # Se ejecuta al hacer push a la rama main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'  # Usa la versión de Node.js que necesites

      - name: Install dependencies and build Angular
        run: |
          npm install
          npm run build -- --configuration=production  # Ajusta según tu angular.json

      - name: Deploy to Netlify
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=dist/prueba-tecnica/browser --prod  # Reemplaza "dist/..." con tu carpeta de build
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}  # Opcional: Si tienes múltiples sitios
